### ISSUE TITLE
Error en common book

### ISSUE THREAD

**Issue by BrandonMolinaCasai** [casai-org/casai_odoo_issues#4]
Uncaught an exception occurred in a caller-provided callback function
https://odoo.casai.com/web/content/5412-5822a74/web.assets_backend.js:2221
Traceback:
undefined

quiero importar un archivo en formato CSV y me aparece el mensaje anterior.

**Comment by JorgeJuarezCasai** [comment]
revisa tu cache, de ser posible borrarlo o iniciar en incognito
