### ISSUE TITLE
Employee name overwritten by user name

### ISSUE THREAD

**Issue by miguel-magos** [casai-org/casai_odoo_issues#8]
**Describe the bug**
Once the employee is linked to the odoo user, some modifications to the employee info will overwrite the employee name with the username. 

**To Reproduce**
1. Go to Employee section
2. Click on edit any employee
3. Modify work email and save

**Expected behavior**
The official employee name should not be overwritten by the user defined username

**Comment by JorgeJuarezCasai** [comment]
_sync_user method override employee info when the linked user or user linked data has been updated, this functionality will be removed.
 
![image](https://user-images.githubusercontent.com/59581653/86983354-4a394380-c151-11ea-8e93-21cf0fe4fd81.png)
